### ISSUE TITLE
Server sending invalid dates

### ISSUE THREAD

**Issue by xvasek** [fossar/selfoss#1246]
Hello,

I have problems with development builds in firefox. If the list of articles is empty, I see the gui, but when there is at least one article, i see only background (in all window sizes):

![obrazek](https://user-images.githubusercontent.com/79145121/108059414-c257d800-7055-11eb-83bc-cd85b346a05d.png)

In console I see "invalid date" errors.

![obrazek](https://user-images.githubusercontent.com/79145121/108062022-7a3ab480-7059-11eb-8e35-c8eb3ac08ec2.png)

In Edge selfoss more or less works. (ie. "R" for reload does not work, but I don't know, if it worked before, I only used Edge for test.)

**Comment by jtojnar** [comment]
Thanks for reporting.

Could you try dumping the date using the following patch?

```patch
diff --git a/assets/js/templates/Item.jsx b/assets/js/templates/Item.jsx
index 275365ae..7c386541 100644
--- a/assets/js/templates/Item.jsx
+++ b/assets/js/templates/Item.jsx
@@ -295,6 +295,8 @@ export default function Item({ item, selected, expanded, setNavExpanded }) {
     const relDate = selfoss.ui.datetimeRelative(item.datetime);
     const shares = selfoss.shares.getAll();
 
+    console.log(item.datetime);
+
     return (
         <div data-entry-id={item.id}
             data-entry-source={item.source}
```

Or adding debugger breakpoint to the affected line

https://github.com/fossar/selfoss/blob/6fb9a65609dd9f1331f7e3cd6e534a3f937d25a1/assets/js/templates/Item.jsx#L301

and checking what the date is that way?

By the way, which development build do you have? And do you use offline mode?

**Comment by jtojnar** [comment]
The <kbd>r</kbd> is a known regression, just forgot about it. Sorry, will push a fix soon.

**Comment by jtojnar** [comment]
Actually, just dumping the value will probably not give us enough info. I pushed a change that hopefully will: https://github.com/fossar/selfoss/commit/fce8eafc5c050f159109ce58c2d46f3b70795e14

**Comment by jtojnar** [comment]
The <kbd>r</kbd> shortcut should be now fixed at least.

**Comment by xvasek** [comment]
Thank you, I'm confirming "r" now works and navigation panel doesn't disappear when items are in list - so far so good. After loading the page, items are still not displayed and I have redish error message:

Chyba načítání: Invalid date detected: “2021-02-16 22:45:05+01”

The problem IMHO is "+01" in the date, but you are the developer. :-)

**Comment by jtojnar** [comment]
The `+01` is a timezone offset. The issue is that it is missing minutes for some reason (should be `+01:00`). What PHP version do you use?

**Comment by jtojnar** [comment]
Could you search for the date in the last XHR response before the error?

![image](https://user-images.githubusercontent.com/705123/108128584-3ffb0280-70ad-11eb-86c2-76d27e797d2b.png)

**Comment by xvasek** [comment]
My installation is Debian 10 Buster and php 7.3.19-1~deb10u1. I'm using postgres 11 (just upgraded from 9.6 now - no change).

In XHR response all datetimes have wrong format - same as above.

![obrazek](https://user-images.githubusercontent.com/79145121/108184690-c47c6e00-710b-11eb-8695-f6c12145df25.png)

**Comment by jtojnar** [comment]
Thanks again for reporting, I just pushed a fix. It should work with all three supported database engines according to my tests.

**Comment by xvasek** [comment]
Works perfectly, thx. :-)
