### ISSUE TITLE
Refresh keyboard shortcut issues in 2.19

### ISSUE THREAD

**Issue by baz4096** [fossar/selfoss#1405]
I'm used to browsing my feeds with keyboard shortcuts, using tags to read a specific subject, displaying unread items.
As I read down the list, I use 'J' to navigate to each item in turn, 'V' to open items and occasionally I press 'R' to clean up the list.

On 2.18, 'R' happily refreshed the feed, hiding the read items and displaying any newly fetched ones. 

On 2.19, this works intermittently, sometimes working, but often causing some kind of reload (in Chrome 109.0.5414.120 it shows the "Waiting for URL...." at the bottom of the window), but ultimately doing nothing to the list; unread items remain towards the bottom, read items remain at the top. Seems to happen more frequently with longer (>50) lists of unread items.

**Comment by jtojnar** [comment]
Thanks for reporting. I wonder if this is the same as https://github.com/fossar/selfoss/issues/1388. Would you be able to test the [latest snapshot](https://cloudsmith.io/~fossar/repos/selfoss-git/packages/?q=version%3Alatest)?

**Comment by baz4096** [comment]
> Thanks for reporting. I wonder if this is the same as #1388. Would you be able to test the [latest snapshot](https://cloudsmith.io/~fossar/repos/selfoss-git/packages/?q=version%3Alatest)?

Just updated to your indicated snapshot - I'll report back if I notice the issue again. Thanks!

**Comment by baz4096** [comment]
OK, still experiencing this issue. Might have narrowed down the steps to reproduce. I have a list of tagged unread items that's currently 51 items long. Refresh the page, click on the tag, scroll to the bottom - triggers more items to load - open an item and then press R. Not a lot happens! Hope this helps.

**Comment by baz4096** [comment]
>Not a lot happens!
Actually I was wrong, it seems to add the 51st item over and over with each press of 'R'

**Comment by thewholelifetolearn** [comment]
I'm using 2.20 and the refresh shortcut adds and adds the existing items. They just repeat. I didn't have this behaviour on 2.19

**Comment by jtojnar** [comment]
I am not able to reproduce. It might have actually been fixed by https://github.com/fossar/selfoss/pull/1458. Could you please check the [latest snapshot](https://cloudsmith.io/~fossar/repos/selfoss-git/packages/?q=version%3Alatest)?

**Comment by thewholelifetolearn** [comment]
I have tried the latest snapshot ([283ceaa](https://github.com/fossar/selfoss/commit/283ceaabe9ea72196a3566649f4db944dd5fe7e3)) but I still have the issue.

![image](https://github.com/fossar/selfoss/assets/823564/638276fa-8053-4adf-83c2-26269322424a)
